import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import type { Scenario } from "./types.js";

// scenarios.json is generated by `npm run scenarios:build`, which fetches each quake from
// the USGS catalog. It is committed so a replay never needs the network during the demo.
export const scenariosPath = fileURLToPath(new URL("../scenarios.json", import.meta.url));

export function loadScenarios(path = scenariosPath): Scenario[] {
  return JSON.parse(readFileSync(path, "utf8")) as Scenario[];
}

// Shape for GET /replay/scenarios (docs/api.md §3.6).
export function toScenarioSummary(s: Scenario) {
  return {
    id: s.id,
    label: s.label,
    magnitude: s.input.magnitude,
    expectedOutcome: s.expectedOutcome,
  };
}
