[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
reliefpool = "7vBwrt8cAfrNHWNfCddQPRVdhbdKV8VhgP2xgq6qWsj3"

[programs.localnet]
reliefpool = "7vBwrt8cAfrNHWNfCddQPRVdhbdKV8VhgP2xgq6qWsj3"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx mocha --import=tsx -t 1000000 tests/**/*.ts"
